# Generated by Django 4.1.3 on 2022-12-13 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('comment_like', models.IntegerField(default=0, verbose_name='Like')),
                ('comment_dislike', models.IntegerField(default=0, verbose_name='Dislike')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=88, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
                ('main_image', models.ImageField(upload_to='news', verbose_name='Main image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='news.comments', verbose_name='Comment')),
            ],
        ),
    ]
